version: '2'

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

volumes:
  {domain}-mysql_data:
    driver: local

services:
  {domain}-mysql:
    image: mysql:5.6
    container_name: {domain}-mysql
    volumes:
      - {domain}-mysql_data:/var/lib/mysql
      - .:/var/www/app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  {domain}-app:
    image: webdevops/php-apache-dev:7.0
#    build:
#      dockerfile: ./.docker/app/Dockerfile
#      context: .
    container_name: {domain}-app
#    restart: always
    networks:
      - reverse-proxy
    volumes:
      - .:/var/www/app
    depends_on:
      - {domain}-mysql
    links:
      - {domain}-mysql
    environment:
      - VIRTUAL_HOST={domain}
      - WEB_DOCUMENT_ROOT="/var/www/app/public"
#      - LETSENCRYPT_EMAIL=
#      - LETSENCRYPT_HOST=
#      - PHP_DEBUGGER="xdebug"
# export XDEBUG_REMOTE_HOST=$(ifconfig wlan0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
#      - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
#      - XDEBUG_REMOTE_AUTOSTART=1
#    expose:
#      - 9000

